[build]
  command = "npm run build:netlify"
  publish = "dist/CV/browser"
  functions = "dist/CV/server"

[functions]
  directory = "dist/CV/server"
  included_files = ["*.mjs", "*.json"]
  external_node_modules = ["@angular/core", "@angular/common", "@angular/platform-server", "@angular/platform-browser", "rxjs", "zone.js"]

[[plugins]]
  package = "@netlify/angular-runtime"

[build.environment]
  ANGULAR_SSR = "true"
  NODE_VERSION = "20.19.0"

[[edge_functions]]
  function = "angular-ssr"
  path = "/*"

# Remove the problematic function configurations and let the Angular runtime handle the function naming
[functions]
  included_files = ["dist/CV/server/**"]
  external_node_modules = ["@angular/*"]
