[build]
  command = "npm run build:netlify"
  publish = "dist/CV/browser"
  functions = "dist/CV/server"

[[plugins]]
  package = "@netlify/angular-runtime"

[build.environment]
  ANGULAR_SSR = "true"
  NODE_VERSION = "20.19.0"

[[edge_functions]]
  function = "render"
  path = "/*"

[functions]
  directory = "dist/CV/server"
  included_files = ["dist/CV/server/index.server.html"]
