[build]
  command = "npm run build:netlify"
  publish = "dist/CV/browser"
  functions = "dist/CV/server"

[[plugins]]
  package = "@netlify/angular-runtime"

[build.environment]
  ANGULAR_SSR = "true"
  NODE_VERSION = "20.19.0"

[[edge_functions]]
  function = "angular-ssr"
  path = "/*"

[[functions]]
  included_files = ["dist/CV/server/**"]
  external_node_modules = ["@angular/*"]

[functions."server-main"]
  included_files = ["dist/CV/server/main.server.mjs"]

[functions."server-polyfills"]
  included_files = ["dist/CV/server/polyfills.server.mjs"]
